<?php

/**
 * @file
 * Module file for text and image alignment module
 */

/**
 * @defgroup alignment Text and image alignment
 * @ingroup austese
 * @{
 * Text and Image alignment tool
 *
 */

/**
 * Implements hook_help().
 *
 */
function alignment_help($path, $arg) {
  switch ($path) {
    case 'alignment/edit':
      return t('Alignment tools');

    case 'admin/help#alignment':
      // Help text for the admin section, using the module name in the path.
      return t('AustESE Alignment tools');
  }
}

/**
 * Implements hook_permission().
 *
 */
function alignment_permission() {
  return array(
    'edit alignments' => array(
      'title' => t('Edit Alignment'),
      'description' => t('Allow users to create and edit alignments'),
    ),
    'view alignments' => array(
      'title' => t('View Alignment'),
      'description' => t('Allow users to view alignments'),
    ),
  );
}

/**
 * Implements hook_menu().
 *
 *
 * @see hook_menu()
 * @see menu_example
 */
function alignment_menu() {
  // by default any path after this is split and provided as args to alignment_view
  $items['alignment/edit'] = array(
    'title' => 'Edit Alignment',
    'page callback' => 'alignment_view',
    'access arguments' => array('edit alignments'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

/**
 * Constructs a descriptive page.
 *
 */
function alignment_description() {
  return array('#markup' => t('The austese alignment module'));
}
function alignment_view($left=null, $right=null) {
  $module_path = drupal_get_path('module','alignment');
  $rep_module_path = drupal_get_Path('module','repository');
  drupal_add_js($rep_module_path . '/ui/lib/select2/select2.min.js');
  drupal_add_css($rep_module_path . '/ui/lib/select2/select2.css',  array('group' => CSS_DEFAULT, 'every_page' => FALSE));
  drupal_add_css($rep_module_path . '/ui/css/tei.css',  array('group' => CSS_DEFAULT, 'every_page' => FALSE));
  drupal_add_js($rep_module_path . '/ui/lib/handlebars.js');
  drupal_add_js($rep_module_path . '/ui/js/entitytemplates.js');
  drupal_add_js($module_path . '/rangy-core.js');
  drupal_add_js($module_path . '/alignment.js');
  drupal_add_css($module_path . '/alignment.css');
  return theme('alignment_ui',array('left'=>$left, 'right'=>$right));

}
function alignment_theme(){
 return array(
    'alignment_ui' => array(
       'template' => 'alignment_ui',
       'variables' => array('left'=> null, 'right'=>null)
     )
 );
}

function alignment_form_alter(&$form, $form_state, $form_id) {
  $forms = array(
    'user_login_block' => 'user-login-form',
    'user_login' => 'user-login',
    'openid_user_add' => 'openid-user-add',
  );
  if (array_key_exists($form_id, $forms)) {
    $module_path = drupal_get_path('module', 'alignment');
    drupal_add_js($module_path . '/alignment_openid.js');
  }
}